metadata:
  name: app-1
  namespace: argocd
spec:
  destination:
    namespace: develop
    name: kind
  project: default
  sources:
    # Chart template
    - chart: web-site
      repoURL: https://helm.github.io/examples
      targetRevision: 0.1.0
      helm:
        valueFiles:
        - $values/app-of-apps/applications/app-1/values.yaml
    # Values from git
    - repoURL: https://github.com/GA-MO/argocd-dev
      targetRevision: HEAD
      ref: values