apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: develop
  project: default
  sources:
  # Chart template
  - repoURL: 'https://helm.github.io/examples'
    chart: hello-world
    targetRevision: 0.1.0
    helm:
      valueFiles:
      - $values/app-of-apps/applications/app-1/values.yaml
  # Values from git
  - repoURL: 'https://github.com/GA-MO/argocd-dev.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true