apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-2
  namespace: argocd
spec:
  destination:
    namespace: develop
    name: kind
  project: default
  sources:
    # Chart template
    - chart: web-site
      repoURL: https://helm.github.io/examples
      targetRevision: 0.1.0
      helm:
        valueFiles:
        - $values/app-of-apps/applications/values/values-app-2.yaml
    # Values from git
    - repoURL: https://github.com/GA-MO/argocd-dev
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true