apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: thawatchaik/nginx-demo
  newTag: v0.1.4
resources:
- ./resources/ingress.yaml
- ./resources/sv.yaml
- ./resources/deployment.yaml
