---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: demo-web-static
images:
  - name: thawatchaik/nginx-demo
    newTag: v0.1.0
resources:
- ./configurations/ingress.yaml
- ./configurations/service.yaml
- ./configurations/deployment.yaml